// Prove allowlist membership for one member from the tracked leaves file,
// bound to a caller account.
//   ACCOUNT_HASH=<64-hex, no prefix> SECRET_FILE=operator-secret.json node prove.js
// Optional: EMIT_TEST_VECTOR=1 regenerates contracts/src/known_good_proof.rs.
const path = require('path');
const fs = require('fs');
const snarkjs = require('snarkjs');
const { hasher, buildTree, pathFor } = require('./tree');

const DIR = __dirname;
const WASM = path.join(DIR, 'eligibility_js', 'eligibility.wasm');
const ZKEY = path.join(DIR, 'eligibility_final.zkey');
const VKEY = JSON.parse(fs.readFileSync(path.join(DIR, 'verification_key.json'), 'utf8'));
const LEAVES = path.join(DIR, '..', 'allowlist', 'leaves.json');

function proofToBytes(p) {
  const be32 = dec => {
    let hex = BigInt(dec).toString(16);
    if (hex.length > 64) throw new Error(`field element overflow: ${dec}`);
    return Buffer.from(hex.padStart(64, '0'), 'hex');
  };
  return Buffer.concat([
    be32(p.pi_a[0]), be32(p.pi_a[1]),
    be32(p.pi_b[0][0]), be32(p.pi_b[0][1]), be32(p.pi_b[1][0]), be32(p.pi_b[1][1]),
    be32(p.pi_c[0]), be32(p.pi_c[1]),
  ]);
}

(async () => {
  const accountHex = process.env.ACCOUNT_HASH;
  if (!accountHex) throw new Error('set ACCOUNT_HASH=<64-hex account hash, no prefix>');
  const secret = JSON.parse(fs.readFileSync(process.env.SECRET_FILE || 'operator-secret.json', 'utf8'));
  const leaves = JSON.parse(fs.readFileSync(LEAVES, 'utf8'));

  const H = await hasher();
  const index = leaves.indexOf(secret.leaf);
  if (index < 0) throw new Error('your leaf is not in the allowlist yet — submit it and wait for set_root');
  const { root, layers } = buildTree(H, leaves);
  const { pathElements, pathIndices } = pathFor(layers, index);

  const input = {
    identity: secret.identity,
    nullifier: secret.nullifier,
    pathElements,
    pathIndices: pathIndices.map(String),
    root: root.toString(),
    nullifierHash: H([BigInt(secret.nullifier)]).toString(),
    account: BigInt('0x' + accountHex).toString(),
  };

  const { proof, publicSignals } = await snarkjs.groth16.fullProve(input, WASM, ZKEY);
  if (!(await snarkjs.groth16.verify(VKEY, publicSignals, proof))) {
    throw new Error('snarkjs rejected its own proof');
  }
  console.log('snarkjs verify: OK  [root, nullifierHash, account]:', publicSignals);

  const out = {
    proof_hex: proofToBytes(proof).toString('hex'),
    root: publicSignals[0],
    nullifier_hash: publicSignals[1],
    account: publicSignals[2],
    account_hash_hex: accountHex,
  };
  fs.writeFileSync(path.join(DIR, 'proof.json'), JSON.stringify(out, null, 2));
  console.log('wrote proof.json');

  if (process.env.EMIT_TEST_VECTOR === '1') {
    const rs = `// Generated by zk-gate/circuits/prove.js — a real snarkjs proof that verified
// as true against verification_key.json. Proves vk.rs + the verifier agree.
#[test]
fn verifies_known_good_proof_from_snarkjs() {
    use ark_ff::MontFp;
    let proof = Proof {
        a: G1Affine::new_unchecked(MontFp!("${proof.pi_a[0]}"), MontFp!("${proof.pi_a[1]}")),
        b: G2Affine::new_unchecked(
            Fq2::new(MontFp!("${proof.pi_b[0][0]}"), MontFp!("${proof.pi_b[0][1]}")),
            Fq2::new(MontFp!("${proof.pi_b[1][0]}"), MontFp!("${proof.pi_b[1][1]}")),
        ),
        c: G1Affine::new_unchecked(MontFp!("${proof.pi_c[0]}"), MontFp!("${proof.pi_c[1]}")),
    };
    let public_inputs: Vec<Fr> = vec![
        MontFp!("${publicSignals[0]}"), // root
        MontFp!("${publicSignals[1]}"), // nullifierHash
        MontFp!("${publicSignals[2]}"), // account
    ];
    let vk = get_verification_key();
    let pvk = prepare_verifying_key(&vk);
    assert!(
        Groth16::<Bn254>::verify_with_processed_vk(&pvk, &public_inputs, &proof).unwrap_or(false),
        "Rust verifier rejected a proof snarkjs verified as true"
    );
}
`;
    fs.writeFileSync(path.join(DIR, '..', '..', 'contracts', 'src', 'known_good_proof.rs'), rs);
    console.log('wrote contracts/src/known_good_proof.rs');
  }
  process.exit(0);
})();
